"$schema" = "node_modules/wrangler/config-schema.json"
name = "southasianfashion"
compatibility_date = "2026-05-04"
compatibility_flags = ["nodejs_compat"]
main = "@tanstack/react-start/server-entry"

[observability]
enabled = true
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1


[vars]
SITE_URL = "https://southasianfashion.ca"
R2_PUBLIC_URL = "https://media.southasianfashion.ca"
CLOUDFLARE_WEB_ANALYTICS_TOKEN = ""
ADMIN_EMAIL = "denniarems@gmail.com,binumv1998@gmail.com,binumv19982023@gmail.com,babusimon30@gmail.com"
SENDER_EMAIL = "no-replay@southasianfashion.ca"

[[d1_databases]]
binding = "DB"
database_name = "southasianfashion-prod"
database_id = "5978dc7c-a653-4e03-bb02-fe5fa9549c82"
preview_database_id = "5978dc7c-a653-4e03-bb02-fe5fa9549c82"
migrations_dir = "migrations-d1"

[[r2_buckets]]
binding = "MEDIA_BUCKET"
bucket_name = "southasianfashion-media"
preview_bucket_name = "southasianfashion-media-preview"

[[analytics_engine_datasets]]
binding = "ANALYTICS"
dataset = "southasianfashion_events"
