"$schema" = "node_modules/wrangler/config-schema.json"
name = "southasianfashion"
compatibility_date = "2026-05-04"
compatibility_flags = ["nodejs_compat"]
main = "@tanstack/react-start/server-entry"

[observability]
enabled = false
head_sampling_rate = 1

[observability.logs]
enabled = true
head_sampling_rate = 1
persist = true
invocation_logs = true

[observability.traces]
enabled = false
persist = true
head_sampling_rate = 1


[vars]
SITE_URL = "https://southasianfashion.example"
R2_PUBLIC_URL = "https://media.example.com"
ADMIN_EMAIL = "admin@example.com"
SENDER_EMAIL = "SouthAsianFashion <admin@example.com>"

[[d1_databases]]
binding = "DB"
database_name = "southasianfashion-prod"
database_id = "5978dc7c-a653-4e03-bb02-fe5fa9549c82"
preview_database_id = "5978dc7c-a653-4e03-bb02-fe5fa9549c82"
migrations_dir = "migrations-d1"

[[r2_buckets]]
binding = "MEDIA_BUCKET"
bucket_name = "southasianfashion-media"
preview_bucket_name = "southasianfashion-media-preview"
