/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductsIndexRouteImport } from './routes/products/index'
import { Route as CollectionsIndexRouteImport } from './routes/collections/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ProductsSlugRouteImport } from './routes/products/$slug'
import { Route as CollectionsSlugRouteImport } from './routes/collections/$slug'
import { Route as ApiUploadRouteImport } from './routes/api/upload'
import { Route as ApiAnalyticsRouteImport } from './routes/api/analytics'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminProtectedRouteRouteImport } from './routes/admin/_protected/route'
import { Route as ApiUploadBatchRouteImport } from './routes/api/upload/batch'
import { Route as AdminProtectedSizeGuidesRouteImport } from './routes/admin/_protected/size-guides'
import { Route as AdminProtectedSettingsRouteImport } from './routes/admin/_protected/settings'
import { Route as AdminProtectedProductsRouteImport } from './routes/admin/_protected/products'
import { Route as AdminProtectedOccasionsRouteImport } from './routes/admin/_protected/occasions'
import { Route as AdminProtectedModelsRouteImport } from './routes/admin/_protected/models'
import { Route as AdminProtectedHeroesRouteImport } from './routes/admin/_protected/heroes'
import { Route as AdminProtectedHeroRouteImport } from './routes/admin/_protected/hero'
import { Route as AdminProtectedDiscountsRouteImport } from './routes/admin/_protected/discounts'
import { Route as AdminProtectedDashboardRouteImport } from './routes/admin/_protected/dashboard'
import { Route as AdminProtectedCustomEnquiriesRouteImport } from './routes/admin/_protected/custom-enquiries'
import { Route as AdminProtectedCollectionsRouteImport } from './routes/admin/_protected/collections'
import { Route as AdminProtectedCategoriesRouteImport } from './routes/admin/_protected/categories'
import { Route as AdminProtectedProductsBatchRouteImport } from './routes/admin/_protected/products/batch'
import { Route as AdminProtectedProductsAddRouteImport } from './routes/admin/_protected/products/add'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsIndexRoute = CollectionsIndexRouteImport.update({
  id: '/collections/',
  path: '/collections/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/products/$slug',
  path: '/products/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsSlugRoute = CollectionsSlugRouteImport.update({
  id: '/collections/$slug',
  path: '/collections/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnalyticsRoute = ApiAnalyticsRouteImport.update({
  id: '/api/analytics',
  path: '/api/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProtectedRouteRoute = AdminProtectedRouteRouteImport.update({
  id: '/admin/_protected',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadBatchRoute = ApiUploadBatchRouteImport.update({
  id: '/batch',
  path: '/batch',
  getParentRoute: () => ApiUploadRoute,
} as any)
const AdminProtectedSizeGuidesRoute =
  AdminProtectedSizeGuidesRouteImport.update({
    id: '/size-guides',
    path: '/size-guides',
    getParentRoute: () => AdminProtectedRouteRoute,
  } as any)
const AdminProtectedSettingsRoute = AdminProtectedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminProtectedRouteRoute,
} as any)
const AdminProtectedProductsRoute = AdminProtectedProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminProtectedRouteRoute,
} as any)
const AdminProtectedOccasionsRoute = AdminProtectedOccasionsRouteImport.update({
  id: '/occasions',
  path: '/occasions',
  getParentRoute: () => AdminProtectedRouteRoute,
} as any)
const AdminProtectedModelsRoute = AdminProtectedModelsRouteImport.update({
  id: '/models',
  path: '/models',
  getParentRoute: () => AdminProtectedRouteRoute,
} as any)
const AdminProtectedHeroesRoute = AdminProtectedHeroesRouteImport.update({
  id: '/heroes',
  path: '/heroes',
  getParentRoute: () => AdminProtectedRouteRoute,
} as any)
const AdminProtectedHeroRoute = AdminProtectedHeroRouteImport.update({
  id: '/hero',
  path: '/hero',
  getParentRoute: () => AdminProtectedRouteRoute,
} as any)
const AdminProtectedDiscountsRoute = AdminProtectedDiscountsRouteImport.update({
  id: '/discounts',
  path: '/discounts',
  getParentRoute: () => AdminProtectedRouteRoute,
} as any)
const AdminProtectedDashboardRoute = AdminProtectedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminProtectedRouteRoute,
} as any)
const AdminProtectedCustomEnquiriesRoute =
  AdminProtectedCustomEnquiriesRouteImport.update({
    id: '/custom-enquiries',
    path: '/custom-enquiries',
    getParentRoute: () => AdminProtectedRouteRoute,
  } as any)
const AdminProtectedCollectionsRoute =
  AdminProtectedCollectionsRouteImport.update({
    id: '/collections',
    path: '/collections',
    getParentRoute: () => AdminProtectedRouteRoute,
  } as any)
const AdminProtectedCategoriesRoute =
  AdminProtectedCategoriesRouteImport.update({
    id: '/categories',
    path: '/categories',
    getParentRoute: () => AdminProtectedRouteRoute,
  } as any)
const AdminProtectedProductsBatchRoute =
  AdminProtectedProductsBatchRouteImport.update({
    id: '/batch',
    path: '/batch',
    getParentRoute: () => AdminProtectedProductsRoute,
  } as any)
const AdminProtectedProductsAddRoute =
  AdminProtectedProductsAddRouteImport.update({
    id: '/add',
    path: '/add',
    getParentRoute: () => AdminProtectedProductsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AdminProtectedRouteRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/api/analytics': typeof ApiAnalyticsRoute
  '/api/upload': typeof ApiUploadRouteWithChildren
  '/collections/$slug': typeof CollectionsSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/collections/': typeof CollectionsIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/admin/categories': typeof AdminProtectedCategoriesRoute
  '/admin/collections': typeof AdminProtectedCollectionsRoute
  '/admin/custom-enquiries': typeof AdminProtectedCustomEnquiriesRoute
  '/admin/dashboard': typeof AdminProtectedDashboardRoute
  '/admin/discounts': typeof AdminProtectedDiscountsRoute
  '/admin/hero': typeof AdminProtectedHeroRoute
  '/admin/heroes': typeof AdminProtectedHeroesRoute
  '/admin/models': typeof AdminProtectedModelsRoute
  '/admin/occasions': typeof AdminProtectedOccasionsRoute
  '/admin/products': typeof AdminProtectedProductsRouteWithChildren
  '/admin/settings': typeof AdminProtectedSettingsRoute
  '/admin/size-guides': typeof AdminProtectedSizeGuidesRoute
  '/api/upload/batch': typeof ApiUploadBatchRoute
  '/admin/products/add': typeof AdminProtectedProductsAddRoute
  '/admin/products/batch': typeof AdminProtectedProductsBatchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin': typeof AdminIndexRoute
  '/admin/login': typeof AdminLoginRoute
  '/api/analytics': typeof ApiAnalyticsRoute
  '/api/upload': typeof ApiUploadRouteWithChildren
  '/collections/$slug': typeof CollectionsSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/collections': typeof CollectionsIndexRoute
  '/products': typeof ProductsIndexRoute
  '/admin/categories': typeof AdminProtectedCategoriesRoute
  '/admin/collections': typeof AdminProtectedCollectionsRoute
  '/admin/custom-enquiries': typeof AdminProtectedCustomEnquiriesRoute
  '/admin/dashboard': typeof AdminProtectedDashboardRoute
  '/admin/discounts': typeof AdminProtectedDiscountsRoute
  '/admin/hero': typeof AdminProtectedHeroRoute
  '/admin/heroes': typeof AdminProtectedHeroesRoute
  '/admin/models': typeof AdminProtectedModelsRoute
  '/admin/occasions': typeof AdminProtectedOccasionsRoute
  '/admin/products': typeof AdminProtectedProductsRouteWithChildren
  '/admin/settings': typeof AdminProtectedSettingsRoute
  '/admin/size-guides': typeof AdminProtectedSizeGuidesRoute
  '/api/upload/batch': typeof ApiUploadBatchRoute
  '/admin/products/add': typeof AdminProtectedProductsAddRoute
  '/admin/products/batch': typeof AdminProtectedProductsBatchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/_protected': typeof AdminProtectedRouteRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/api/analytics': typeof ApiAnalyticsRoute
  '/api/upload': typeof ApiUploadRouteWithChildren
  '/collections/$slug': typeof CollectionsSlugRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/collections/': typeof CollectionsIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/admin/_protected/categories': typeof AdminProtectedCategoriesRoute
  '/admin/_protected/collections': typeof AdminProtectedCollectionsRoute
  '/admin/_protected/custom-enquiries': typeof AdminProtectedCustomEnquiriesRoute
  '/admin/_protected/dashboard': typeof AdminProtectedDashboardRoute
  '/admin/_protected/discounts': typeof AdminProtectedDiscountsRoute
  '/admin/_protected/hero': typeof AdminProtectedHeroRoute
  '/admin/_protected/heroes': typeof AdminProtectedHeroesRoute
  '/admin/_protected/models': typeof AdminProtectedModelsRoute
  '/admin/_protected/occasions': typeof AdminProtectedOccasionsRoute
  '/admin/_protected/products': typeof AdminProtectedProductsRouteWithChildren
  '/admin/_protected/settings': typeof AdminProtectedSettingsRoute
  '/admin/_protected/size-guides': typeof AdminProtectedSizeGuidesRoute
  '/api/upload/batch': typeof ApiUploadBatchRoute
  '/admin/_protected/products/add': typeof AdminProtectedProductsAddRoute
  '/admin/_protected/products/batch': typeof AdminProtectedProductsBatchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/admin'
    | '/admin/login'
    | '/api/analytics'
    | '/api/upload'
    | '/collections/$slug'
    | '/products/$slug'
    | '/admin/'
    | '/collections/'
    | '/products/'
    | '/admin/categories'
    | '/admin/collections'
    | '/admin/custom-enquiries'
    | '/admin/dashboard'
    | '/admin/discounts'
    | '/admin/hero'
    | '/admin/heroes'
    | '/admin/models'
    | '/admin/occasions'
    | '/admin/products'
    | '/admin/settings'
    | '/admin/size-guides'
    | '/api/upload/batch'
    | '/admin/products/add'
    | '/admin/products/batch'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/admin'
    | '/admin/login'
    | '/api/analytics'
    | '/api/upload'
    | '/collections/$slug'
    | '/products/$slug'
    | '/collections'
    | '/products'
    | '/admin/categories'
    | '/admin/collections'
    | '/admin/custom-enquiries'
    | '/admin/dashboard'
    | '/admin/discounts'
    | '/admin/hero'
    | '/admin/heroes'
    | '/admin/models'
    | '/admin/occasions'
    | '/admin/products'
    | '/admin/settings'
    | '/admin/size-guides'
    | '/api/upload/batch'
    | '/admin/products/add'
    | '/admin/products/batch'
  id:
    | '__root__'
    | '/'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/admin/_protected'
    | '/admin/login'
    | '/api/analytics'
    | '/api/upload'
    | '/collections/$slug'
    | '/products/$slug'
    | '/admin/'
    | '/collections/'
    | '/products/'
    | '/admin/_protected/categories'
    | '/admin/_protected/collections'
    | '/admin/_protected/custom-enquiries'
    | '/admin/_protected/dashboard'
    | '/admin/_protected/discounts'
    | '/admin/_protected/hero'
    | '/admin/_protected/heroes'
    | '/admin/_protected/models'
    | '/admin/_protected/occasions'
    | '/admin/_protected/products'
    | '/admin/_protected/settings'
    | '/admin/_protected/size-guides'
    | '/api/upload/batch'
    | '/admin/_protected/products/add'
    | '/admin/_protected/products/batch'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  AdminProtectedRouteRoute: typeof AdminProtectedRouteRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  ApiAnalyticsRoute: typeof ApiAnalyticsRoute
  ApiUploadRoute: typeof ApiUploadRouteWithChildren
  CollectionsSlugRoute: typeof CollectionsSlugRoute
  ProductsSlugRoute: typeof ProductsSlugRoute
  AdminIndexRoute: typeof AdminIndexRoute
  CollectionsIndexRoute: typeof CollectionsIndexRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/': {
      id: '/collections/'
      path: '/collections'
      fullPath: '/collections/'
      preLoaderRoute: typeof CollectionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/products/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections/$slug': {
      id: '/collections/$slug'
      path: '/collections/$slug'
      fullPath: '/collections/$slug'
      preLoaderRoute: typeof CollectionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/analytics': {
      id: '/api/analytics'
      path: '/api/analytics'
      fullPath: '/api/analytics'
      preLoaderRoute: typeof ApiAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_protected': {
      id: '/admin/_protected'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminProtectedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload/batch': {
      id: '/api/upload/batch'
      path: '/batch'
      fullPath: '/api/upload/batch'
      preLoaderRoute: typeof ApiUploadBatchRouteImport
      parentRoute: typeof ApiUploadRoute
    }
    '/admin/_protected/size-guides': {
      id: '/admin/_protected/size-guides'
      path: '/size-guides'
      fullPath: '/admin/size-guides'
      preLoaderRoute: typeof AdminProtectedSizeGuidesRouteImport
      parentRoute: typeof AdminProtectedRouteRoute
    }
    '/admin/_protected/settings': {
      id: '/admin/_protected/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminProtectedSettingsRouteImport
      parentRoute: typeof AdminProtectedRouteRoute
    }
    '/admin/_protected/products': {
      id: '/admin/_protected/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProtectedProductsRouteImport
      parentRoute: typeof AdminProtectedRouteRoute
    }
    '/admin/_protected/occasions': {
      id: '/admin/_protected/occasions'
      path: '/occasions'
      fullPath: '/admin/occasions'
      preLoaderRoute: typeof AdminProtectedOccasionsRouteImport
      parentRoute: typeof AdminProtectedRouteRoute
    }
    '/admin/_protected/models': {
      id: '/admin/_protected/models'
      path: '/models'
      fullPath: '/admin/models'
      preLoaderRoute: typeof AdminProtectedModelsRouteImport
      parentRoute: typeof AdminProtectedRouteRoute
    }
    '/admin/_protected/heroes': {
      id: '/admin/_protected/heroes'
      path: '/heroes'
      fullPath: '/admin/heroes'
      preLoaderRoute: typeof AdminProtectedHeroesRouteImport
      parentRoute: typeof AdminProtectedRouteRoute
    }
    '/admin/_protected/hero': {
      id: '/admin/_protected/hero'
      path: '/hero'
      fullPath: '/admin/hero'
      preLoaderRoute: typeof AdminProtectedHeroRouteImport
      parentRoute: typeof AdminProtectedRouteRoute
    }
    '/admin/_protected/discounts': {
      id: '/admin/_protected/discounts'
      path: '/discounts'
      fullPath: '/admin/discounts'
      preLoaderRoute: typeof AdminProtectedDiscountsRouteImport
      parentRoute: typeof AdminProtectedRouteRoute
    }
    '/admin/_protected/dashboard': {
      id: '/admin/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminProtectedDashboardRouteImport
      parentRoute: typeof AdminProtectedRouteRoute
    }
    '/admin/_protected/custom-enquiries': {
      id: '/admin/_protected/custom-enquiries'
      path: '/custom-enquiries'
      fullPath: '/admin/custom-enquiries'
      preLoaderRoute: typeof AdminProtectedCustomEnquiriesRouteImport
      parentRoute: typeof AdminProtectedRouteRoute
    }
    '/admin/_protected/collections': {
      id: '/admin/_protected/collections'
      path: '/collections'
      fullPath: '/admin/collections'
      preLoaderRoute: typeof AdminProtectedCollectionsRouteImport
      parentRoute: typeof AdminProtectedRouteRoute
    }
    '/admin/_protected/categories': {
      id: '/admin/_protected/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminProtectedCategoriesRouteImport
      parentRoute: typeof AdminProtectedRouteRoute
    }
    '/admin/_protected/products/batch': {
      id: '/admin/_protected/products/batch'
      path: '/batch'
      fullPath: '/admin/products/batch'
      preLoaderRoute: typeof AdminProtectedProductsBatchRouteImport
      parentRoute: typeof AdminProtectedProductsRoute
    }
    '/admin/_protected/products/add': {
      id: '/admin/_protected/products/add'
      path: '/add'
      fullPath: '/admin/products/add'
      preLoaderRoute: typeof AdminProtectedProductsAddRouteImport
      parentRoute: typeof AdminProtectedProductsRoute
    }
  }
}

interface AdminProtectedProductsRouteChildren {
  AdminProtectedProductsAddRoute: typeof AdminProtectedProductsAddRoute
  AdminProtectedProductsBatchRoute: typeof AdminProtectedProductsBatchRoute
}

const AdminProtectedProductsRouteChildren: AdminProtectedProductsRouteChildren =
  {
    AdminProtectedProductsAddRoute: AdminProtectedProductsAddRoute,
    AdminProtectedProductsBatchRoute: AdminProtectedProductsBatchRoute,
  }

const AdminProtectedProductsRouteWithChildren =
  AdminProtectedProductsRoute._addFileChildren(
    AdminProtectedProductsRouteChildren,
  )

interface AdminProtectedRouteRouteChildren {
  AdminProtectedCategoriesRoute: typeof AdminProtectedCategoriesRoute
  AdminProtectedCollectionsRoute: typeof AdminProtectedCollectionsRoute
  AdminProtectedCustomEnquiriesRoute: typeof AdminProtectedCustomEnquiriesRoute
  AdminProtectedDashboardRoute: typeof AdminProtectedDashboardRoute
  AdminProtectedDiscountsRoute: typeof AdminProtectedDiscountsRoute
  AdminProtectedHeroRoute: typeof AdminProtectedHeroRoute
  AdminProtectedHeroesRoute: typeof AdminProtectedHeroesRoute
  AdminProtectedModelsRoute: typeof AdminProtectedModelsRoute
  AdminProtectedOccasionsRoute: typeof AdminProtectedOccasionsRoute
  AdminProtectedProductsRoute: typeof AdminProtectedProductsRouteWithChildren
  AdminProtectedSettingsRoute: typeof AdminProtectedSettingsRoute
  AdminProtectedSizeGuidesRoute: typeof AdminProtectedSizeGuidesRoute
}

const AdminProtectedRouteRouteChildren: AdminProtectedRouteRouteChildren = {
  AdminProtectedCategoriesRoute: AdminProtectedCategoriesRoute,
  AdminProtectedCollectionsRoute: AdminProtectedCollectionsRoute,
  AdminProtectedCustomEnquiriesRoute: AdminProtectedCustomEnquiriesRoute,
  AdminProtectedDashboardRoute: AdminProtectedDashboardRoute,
  AdminProtectedDiscountsRoute: AdminProtectedDiscountsRoute,
  AdminProtectedHeroRoute: AdminProtectedHeroRoute,
  AdminProtectedHeroesRoute: AdminProtectedHeroesRoute,
  AdminProtectedModelsRoute: AdminProtectedModelsRoute,
  AdminProtectedOccasionsRoute: AdminProtectedOccasionsRoute,
  AdminProtectedProductsRoute: AdminProtectedProductsRouteWithChildren,
  AdminProtectedSettingsRoute: AdminProtectedSettingsRoute,
  AdminProtectedSizeGuidesRoute: AdminProtectedSizeGuidesRoute,
}

const AdminProtectedRouteRouteWithChildren =
  AdminProtectedRouteRoute._addFileChildren(AdminProtectedRouteRouteChildren)

interface ApiUploadRouteChildren {
  ApiUploadBatchRoute: typeof ApiUploadBatchRoute
}

const ApiUploadRouteChildren: ApiUploadRouteChildren = {
  ApiUploadBatchRoute: ApiUploadBatchRoute,
}

const ApiUploadRouteWithChildren = ApiUploadRoute._addFileChildren(
  ApiUploadRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  AdminProtectedRouteRoute: AdminProtectedRouteRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  ApiAnalyticsRoute: ApiAnalyticsRoute,
  ApiUploadRoute: ApiUploadRouteWithChildren,
  CollectionsSlugRoute: CollectionsSlugRoute,
  ProductsSlugRoute: ProductsSlugRoute,
  AdminIndexRoute: AdminIndexRoute,
  CollectionsIndexRoute: CollectionsIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
